# Generated by Django 5.0.2 on 2024-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Фото')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=200, verbose_name='Наименование часов')),
                ('category', models.CharField(choices=[('new', 'Новые'), ('popular', 'Популярные'), ('Beggar', 'Бюджетные')], max_length=200)),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
