# Generated by Django 5.0.2 on 2024-03-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
